### ISSUE TITLE
Update baza de date de cuvinte

### ISSUE THREAD

**Issue by cbira** [Nicoolaescu/wordle#2]
Adaugarea unui wordlist adevarat, 20-30 de cuvinte sunt prea putine (e ok fara diacritice, e ok si daca e pe limba engleza in loc de romana etc, ideea e sa fie cateva mii de cuvinte)
eg: https://raw.githubusercontent.com/ManiacDC/TypingAid/master/Wordlists/Wordlist%20Romanian.txt

**Comment by Nicoolaescu** [comment]
rezolvat in commit-ul 487306b086e714e899f77922ccd0f85f18ff8545
