### ISSUE TITLE
Parametri de cuvant modificabili fara recompilare

### ISSUE THREAD

**Issue by cbira** [Nicoolaescu/wordle#3]
In codul sursa exista cativa parametri de cuvint (numar litere minim, maxim) care sunt macro-uri, deci daca vrem sa le schimbam valoare trebuie sa recompilam codul sursa. As sugera sa se citeasca dintr-un fisier de setari (eg. setari.txt) in loc sa fie hard-codati.

**Comment by Nicoolaescu** [comment]
Rezolvat in commit-ul 62fa67c1131c7c04a8fd2c5584b27211888614d5
